### PR TITLE
Headings styles, npc-wrapper heading style

### PR DESCRIPTION
**Pull request by tiagoratto**
Changed and added headings styles, changed npc h4 style to align with the stats block.

### CODE REVIEW

**Comment by TK20466** [comment]
I added an H5 and a Caption rule... do we need H6 from this pull?

**Comment by TK20466** [comment]
I don't think the H4 should align with the NPC box because it breaks consistency with other H4 rules.

**Comment by tiagoratto** [comment]
I think I wasn't clear enough:

- H4 aligns left with NPC box only when it right before it, other uses the align is the same as before. You can have a look on http://swrpg.mobeegeek.com
- Current H5 style is the one used as table titles, and we are missing one headline style found on page 15 of Operation Shadowpoint, what I did was to replace H6 style with H5 and change H5 style to the same as of the PDF, which is the same as H4 but blue and right aligned.

**Comment by TK20466** [comment]
Check out commit 63cfddf regarding the H5/H6.

**Comment by tiagoratto** [comment]
Updated my version to the upstream, the changes are:

- A margin when using h1 at the start of a webpage.
- H4 align to the NPC/Starship wrapper as in the books.

**Pull request merged**
